### ISSUE TITLE
Users and devices access

### ISSUE THREAD

**Issue by Cybernemo** [LINKIWI/orion-docker#5]
I always get the following error **There was an error fetching users and devices.Unexpected token N in JSON at position 0**. There is also an erre 404 when calling /api/users.

I use orion-docker behind the reverse-proxy traefik.

Any idea where the problem lies?

**Comment by LINKIWI** [comment]
Can you provide exact reproduction steps and describe specifically the expected and actual behavior?

This works for me:

```bash
$ git clone git@github.com:LINKIWI/orion-docker.git .
$ git checkout 69b05373ed5a9e8db690fb7fa11f8727d5b4375d
$ docker-compose up -d
$ curl localhost:20030/api/users
{"data":[],"message":null,"success":true}
```

**Comment by Cybernemo** [comment]
I am using orion-docker with the reverse proxy traefik. And it seems I am not forwarding the correct port in some way.

**Comment by Cybernemo** [comment]
Here is my docker-compose file I use with traefik:
############# ORION ###############
  db_orion:
    image: mysql:5.7
    container_name: orion_mysql
    restart: always
    labels:
      - traefik.enable=false
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=orion
    networks:
      - internal_orion

  server_orion:
    restart: always
    container_name: orion_server
    labels:
      - traefik.enable=false
    build:
      context: ./orion-docker/orion-server
      args:
        sha: fedb85c8b2980bfc4dea7bf93ca17e059f63b1c1
        database_host: orion_mysql
        database_port: 3306
        database_name: orion
        database_user: root
        database_password: password
    depends_on:
      - db_orion
    networks:
      - internal_orion
  web_orion:
    restart: always
    container_name: orion_web
    build:
      context: ./orion-docker/orion-web
      args:
        sha: 8c18dce19a2199c4c53e1145881d362a05018cd5
        mapbox_api_token: ${MAPBOX_API_TOKEN}
    labels:
      - traefik.backend=orion
      - traefik.frontend.rule=Host:orion.mydomain.com
      - traefik.docker.network=proxy
      - traefik.port=80
      - traefik.enable=true
    ports:
      - 8084:80
    depends_on:
      - server_orion
    networks:
      - internal_orion
      - proxy

All three containers start without problem but the web container does not communicate with the server neither the db. Therefore the web container is not able to access /api/users.

**Comment by LINKIWI** [comment]
You changed the names of the containers, so the nginx path routing defined here is broken: https://github.com/LINKIWI/orion-docker/blob/master/http/nginx.conf

You should either use the default container names for the web and server or change them in nginx.conf.
